spring:
  application:
    name: PATIENT-SERVICE
  datasource:
    url: jdbc:h2:mem:patient
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9000

eureka:
  client:
    serviceUrl:
     defaultZone : http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true